name: CI-Install

on:
  workflow_dispatch:

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: setup node ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    #- name: get yarn cache directory path
    #  id: yarn-cache-dir-path
    #  run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
    #  shell: bash

    #- name: restore yarn cache directory
    #  id: yarn-cache
    #  uses: actions/cache@v3
    #  with:
    #    path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
    #    key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    #    restore-keys: ${{ runner.os }}-yarn-

    #- name: set msvs_version
    #  run: npm config set msvs_version 2017

    - name: install node-gyp
      run: npm install -g node-gyp

    - name: echo npm prefix
      run: echo "$(npm prefix -g)"
      shell: bash

    - name: set node-gyp path
      run: npm config set node_gyp "$(npm prefix -g)/lib/node_modules/node-gyp/bin/node-gyp.js"
      shell: bash

    - name: install dependencies
      run: yarn --frozen-lockfile

    - name: run tests
      run: yarn test
