name: CI

on:
  push:
    branches: [main]
    paths-ignore: ['**.md']
  pull_request:
    branches: [main]
    paths-ignore: ['**.md']
  workflow_dispatch:

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: setup node ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: restore yarn cache directory
      id: yarn-cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Update node-gyp
      if: matrix.os == 'windows-latest'
      run: |
        $WhereNode = Get-Command node | Select-Object -ExpandProperty Definition
        $NodeDirPath = Split-Path $WhereNode -Parent
        $NodeModulesPath = $NodeDirPath + "\node_modules\npm\node_modules\npm-lifecycle"
        cd $NodeModulesPath
        npm install node-gyp@latest

    - name: Set node-gyp path
      if: matrix.os == 'windows-latest'
      run: |
        npm config set node_gyp "${GITHUB_WORKSPACE}\node_modules\node-gyp\bin\node-gyp.js"

    - name: install dependencies
      run: yarn --frozen-lockfile

    - name: run tests
      run: yarn test
