name: CI

on:
  push:
    branches: [main]
    paths-ignore: ['**.md']
  pull_request:
    branches: [main]
    paths-ignore: ['**.md']
  workflow_dispatch:

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: setup node ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: restore yarn cache directory
      id: yarn-cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: echo-default-env-variables
      run: |
        echo "Home: ${HOME}"
        echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
        echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
        echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
        echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
        echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
        echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
        echo "GITHUB_SHA: ${GITHUB_SHA}"
        echo "GITHUB_REF: ${GITHUB_REF}"

    - name: get node-gyp path
      id: node-gyp-path
      run: echo "::set-output name=path::$(npm prefix)/node_modules/node-gyp/bin/node-gyp.js"

    - name: echo node-gyp path
      run: echo "${{ steps.node-gyp-path.outputs.path }}"

    - name: set node-gyp path
      run: npm config set node_gyp "${{ steps.node-gyp-path.outputs.path }}"

    - name: install dependencies
      run: yarn --frozen-lockfile

    - name: run tests
      run: yarn test
