name: CI

on:
  push:
    branches: [main]
    paths-ignore: ['**.md']
  pull_request:
    branches: [main]
    paths-ignore: ['**.md']
  workflow_dispatch:

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: setup node ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: restore yarn cache directory
      id: yarn-cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: get working directory path
      id: repo-dir-path
      run: echo "::set-output name=path::$($GITHUB_WORKSPACE)"

    - name: echo working directory path
      run: echo "${{ steps.repo-dir-path.outputs.path }}"

    - name: Set node-gyp path
      run: npm config set node_gyp "${{ steps.repo-dir-path.outputs.path }}/node_modules/node-gyp/bin/node-gyp.js"

    - name: install dependencies
      run: yarn --frozen-lockfile

    - name: run tests
      run: yarn test
