name: CI

on:
  workflow_dispatch:

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: setup node ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash

    - name: restore yarn cache directory
      id: yarn-cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-${{ runner.node }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-${{ runner.node }}-yarn-

    - name: get node-gyp cache directory path (linux)
      id: node-gyp-cache-dir-path
      if: runner.os == ubuntu-latest
      run: echo "dir=/temp/.gyp" >> $GITHUB_OUTPUT
      shell: bash

    - name: get node-gyp cache directory path (windows)
      id: node-gyp-cache-dir-path
      if: runner.os == windows-latest
      run: echo "dir=C:\temp\.gyp" >> $GITHUB_OUTPUT
      shell: bash

    - name: restore node-gyp cache directory
      id: node-gyp-cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.node-gyp-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-${{ runner.node }}-node-gyp-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-${{ runner.node }}-node-gyp-

    - name: set node-gyp path
      run: npm config set node_gyp "$(npm prefix)/node_modules/node-gyp/bin/node-gyp.js" --location project

    - name: set node-gyp devdir
      run: npm config set devdir "${{ steps.node-gyp-cache-dir-path.outputs.dir }}" --location project

    - name: install dependencies
      run: yarn --frozen-lockfile --verbose

    - name: run tests
      run: yarn test
