name: CI

on:
  workflow_dispatch:

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: setup node ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: get npm modules cache directory path
      id: node_modules-cache-dir-path
      run: echo "dir=$(npm prefix)/node_modules" >> $GITHUB_OUTPUT
      shell: bash

    - name: restore node_modules cache directory
      id: node_modules-cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.node_modules-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-${{ runner.node }}-node_modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-${{ runner.node }}-node_modules-

    - name: set node-gyp path
      run: npm config set node_gyp "$(npm prefix)/node_modules/node-gyp/bin/node-gyp.js" --location project

    - name: set node-gyp devdir
      run: npm config set devdir "$(npm prefix)/node_modules/node-gyp/tmp/.gyp" --location project

    - name: install dependencies
      run: yarn --frozen-lockfile

    - name: run tests
      run: yarn test
